fiid_india/urls.py
from django.urls import path
from .import views

app_name = 'fiid-india'


urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('about/', views.AboutPageView.as_view(), name='about'),
    path('programs/', views.ProgramsPageView.as_view(), name='programmes'),
    path('objectives/', views.ObjectivesPageView.as_view(), name='objectives'),
    path('contact/', views.ContactPageView.as_view(), name='contact'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fiid_india.urls', namespace='fiid-india')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractUser
from .user_manager import UserManager

class User(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    
    objects = UserManager()

fiid_india/models.py
from django.db import models


class Message(models.Model):
    name = models.CharField(max_length=300)
    email = models.EmailField()
    subject = models.CharField(max_length=300)
    message = models.TextField()

    def __str__(self):
        return str(self.name)

accounts/views.py
from django.shortcuts import render

# Create your views here.

fiid_india/views.py
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.contrib import messages
from django.urls import reverse_lazy
from django.views import generic
from . models import Message


class HomePageView(generic.TemplateView):
    template_name = 'fiid_india/home.html'


class AboutPageView(generic.TemplateView):
    template_name = 'fiid_india/about.html'


class ProgramsPageView(generic.TemplateView):
    template_name = 'fiid_india/programmes.html'


class ObjectivesPageView(generic.TemplateView):
    template_name = 'fiid_india/objectives.html'


class ContactPageView(generic.CreateView):
    model = Message
    template_name = 'fiid_india/contact.html'
    fields = '__all__'
    
    def form_valid(self, form):
        notification = "The message has been sent successfully"
        messages.success(self.request, notification)
        return super(ContactPageView, self).form_valid(form)
    
    def form_invalid(self, form):
        notification = "Couldn't send the message. Please try later"
        messages.error(self.request, notification)
        return super(ContactPageView, self).form_invalid(form)

    def get_success_url(self):
        return reverse_lazy('fiid-india:contact')

fiid_india/templates/fiid_india/about.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'fiid_india/about_page/style.css' %}">
{% endblock styles %}


{% block content %}

{% include 'navbar.html' %}

<section id="about">
    <div class="container">
        <a href="{% url 'fiid-india:home' %}">
            <button class="primary-btn go-back"><i class="fa-solid fa-arrow-left me-2"></i>Goback</button>
        </a>
        <div class="row">
            <div class="col-12 col-lg-6">
                <h3>Who we are</h3>
                <h4 class="quote">"About FIID India: Promoting Integral Development and Empowering
                    Communities in Rural India"</h4>
            </div>
            <div class="col-12 col-lg-6">
                <div class="ratio ratio-16x9 d-none d-lg-block">
                    <img class="w-100"
                        src="https://images.unsplash.com/photo-1511632765486-a01980e01a18?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"
                        alt="">
                </div>
                <div class="ratio ratio-1x1 d-block d-lg-none">
                    <img class="w-100"
                        src="https://images.unsplash.com/photo-1511632765486-a01980e01a18?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"
                        alt="">
                </div>
                <p>
                    Fransalian Initiatives for Integral Development in India (FIID India) is a non-profit
                    organization
                    dedicated to promoting social welfare and economic development in rural communities across
                    India.
                    Our mission is to improve the lives of individuals in underserved areas by providing access to
                    essential services, including healthcare, education, and vocational training.
                </p>

                <p>
                    We recognize that India is a diverse country with a vast array of cultures, traditions, and
                    languages. At FIID India, we believe that every individual, regardless of their caste, creed,
                    religion, community, or language, should have access to these basic services. We work tirelessly
                    to
                    bridge the gap between the rural and urban areas of India, where access to these services is
                    often
                    limited.
                </p>

                <p>
                    Our organization was founded on the belief that development should be holistic and inclusive. We
                    believe that sustainable development can only be achieved by addressing the root causes of
                    poverty
                    and inequality. Our approach is grounded in the principles of integral development, which
                    combines
                    economic, social, and spiritual dimensions of development.
                </p>

                <p>
                    Healthcare is one of the most critical aspects of our work at FIID India. We believe that access
                    to
                    quality healthcare is a fundamental right and that it should be available to everyone,
                    regardless of
                    their economic status. Our healthcare programs focus on improving the overall health of
                    communities
                    by providing access to primary healthcare services, health education, and preventive care. We
                    also
                    organize health camps, which provide basic medical check-ups, medicines, and referrals to
                    specialist
                    doctors.
                </p>

                <p>
                    Education is another core focus of our work at FIID India. We believe that education is the key
                    to
                    breaking the cycle of poverty and inequality. Our education programs aim to provide access to
                    quality education to children in rural areas, who are often denied this opportunity due to
                    various
                    reasons. We work with local schools to improve the quality of education and provide scholarships
                    to
                    students from economically weaker backgrounds. We also organize computer training programs,
                    vocational training, and skill development programs, which equip individuals with the skills
                    necessary to thrive in the modern economy.
                </p>

                <p>
                    In addition to healthcare and education, we also focus on economic development. We believe that
                    sustainable economic development is essential for the long-term wellbeing of communities. Our
                    programs focus on providing vocational training and entrepreneurship development, which help
                    individuals to generate income and become self-sufficient. We also support women's self-help
                    groups,
                    which provide a platform for women to come together and work towards their economic empowerment.
                </p>

                <p>
                    At FIID India, we are committed to building a world where everyone has access to basic
                    healthcare,
                    education, and other essential services. We believe that development should be holistic and
                    inclusive, and we work tirelessly towards achieving this goal. Our work has impacted the lives
                    of
                    thousands of individuals in rural communities across India, and we are proud of the progress we
                    have
                    made so far. However, there is still much work to be done, and we invite you to join us on this
                    journey towards a brighter future for all.
                </p>
            </div>
        </div>
    </div>
</section>

{% include 'footer.html' %}
{% endblock content %}

fiid_india/templates/fiid_india/contact.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'fiid_india/contact_page/style.css' %}">
{% endblock styles %}


{% block content %}

{% include 'navbar.html' %}

<section id="contact">
    <div class="container">
        <a href="{% url 'fiid-india:home' %}">
            <button class="primary-btn go-back"><i class="fa-solid fa-arrow-left me-2"></i>Go back</button>
        </a>
        <div class="container-fluid">
            <div class="text-group">
                <h3>Contact</h3>
                <span class="quote">"Have a question or feedback? We're all ears. Get in touch with us
                    today."</span>
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-success alert-dismissible fade show mb-3 mt-3" role="alert">
                            {{message}}
                        <button type="button" class="btn-close shadow-none" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="row row-cols-1 row-cols-lg-2 g-4">
                <div class="col">
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="exampleFormControlInput1" class="form-label">Full Name</label>
                            <input type="text" class="form-control" name="name">
                        </div>
                        <div class="mb-3">
                            <label for="exampleFormControlInput1" class="form-label">Email address</label>
                            <input type="email" class="form-control" name="email">
                        </div>
                        <div class="mb-3">
                            <label for="exampleFormControlInput1" class="form-label">Subject</label>
                            <input type="text" class="form-control" name="subject">
                        </div>
                        <div class="mb-3">
                            <label for="exampleFormControlTextarea1" class="form-label">Message</label>
                            <textarea class="form-control" name="message" rows="6"></textarea>
                        </div>
                        <button type="submit" class="primary-btn">Send message</button>
                    </form>
                </div>

                <div class="container d-block d-lg-none pt-3">
                    <hr>
                </div>

                <div class="col">
                    <div class="wrap d-lg-flex justify-content-center">
                        <div class="address">
                            <h5 class="mb-3"><u>Contact Address</u></h5>
                            <p>Address Line 1</p>
                            <p>Address Line 2</p>
                            <p>District, State</p>
                            <p>Country</p>
                            <p>Pincode</p>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>

{% include 'footer.html' %}
{% endblock content %}

fiid_india/templates/fiid_india/home.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'fiid_india/home_page/style.css' %}">
{% endblock styles %}


{% block content %}

{% include 'navbar.html' %}

<section id="hero">
    <div class="container">
        <div class="title-group">
            <h4>Together, <span class="special-mention">we can make a difference</span></h4>
            <a href="{% url 'fiid-india:programmes' %}">
                <button class="primary-btn d-flex align-items-center"><span class="text">View Our
                        Programmes</span><i class="fa-solid fa-arrow-right ms-2"></i></button>
            </a>
        </div>
    </div>
</section>

<section id="about">
    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-6">
                <h3>Who we are</h3>
            </div>
            <div class="col-12 col-lg-6">
                <div class="ratio ratio-16x9 d-lg-block d-none">
                    <img class="w-100"
                        src="https://images.unsplash.com/photo-1609234656388-0ff363383899?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1632&q=80"
                        alt="">
                </div>
                <div class="ratio ratio-1x1 d-block d-lg-none">
                    <img class="w-100"
                        src="https://images.unsplash.com/photo-1609234656388-0ff363383899?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1632&q=80"
                        alt="">
                </div>

                <p>
                    Fransalian Initiatives for Integral Development in India (FIID India) is a non-profit organization
                    dedicated to promoting social welfare and economic development in rural communities across India.
                    Our mission is to improve the lives of individuals in underserved areas by providing access to
                    essential services, including healthcare, education, and vocational training.
                </p>
                <a href="{% url 'fiid-india:about' %}">
                    <button class="primary-btn d-flex align-items-center">
                        <span class="text">Know more</span>
                        <i class="fa-solid fa-arrow-right ms-2"></i>
                    </button>
                </a>
            </div>
        </div>
    </div>
</section>

<div class="container d-none d-md-block">
    <hr>
</div>

<section id="objectives">
    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-6">
                <h3>What we aim to achieve</h3>
            </div>
            <div class="col-12 col-lg-6">
                <div class="ratio ratio-16x9 d-none d-lg-block">
                    <img class="w-100"
                        src="https://images.unsplash.com/photo-1527525443983-6e60c75fff46?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=685&q=80"
                        alt="">
                </div>
                <div class="ratio ratio-1x1 d-block d-lg-none">
                    <img class="w-100"
                        src="https://images.unsplash.com/photo-1527525443983-6e60c75fff46?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=685&q=80"
                        alt="">
                </div>
                <p>
                    Our mission it promote social welfare and development, improving health and education,
                    providing financial assistance to the needy, and establishing various institutions for the
                    betterment of society. The organization aims to promote social, charitable, humanitarian,
                    religious, and moral ideals, and bring harmony, equality, peace, and tranquility among people
                    from all walks of life.
                </p>
                <a href="{% url 'fiid-india:objectives' %}">
                    <button class="primary-btn d-flex align-items-center">
                        <span class="text">Know more</span>
                        <i class="fa-solid fa-arrow-right ms-2"></i>
                    </button>
                </a>
            </div>
        </div>
    </div>
</section>

{% include 'footer.html' %}
{% endblock content %}

fiid_india/templates/fiid_india/objectives.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'fiid_india/objectives_page/style.css' %}">
{% endblock styles %}


{% block content %}

{% include 'navbar.html' %}

<section id="objectives">
    <div class="container">
        <a href="{% url 'fiid-india:home' %}">
            <button class="primary-btn go-back"><i class="fa-solid fa-arrow-left me-2"></i>Go back</button>
        </a>
        <div class="row">
            <div class="col-12 col-lg-6">

                <h3>What we aim to achieve</h3>
                <h4 class="quote">"Empowering Rural Communities for Sustainable Development: FIID India's
                    Objectives"</h4>

            </div>
            <div class="col-12 col-lg-6">

                <div class="ratio ratio-16x9 d-none d-lg-block">
                    <img class="w-100"
                        src="https://images.unsplash.com/photo-1527525443983-6e60c75fff46?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=685&q=80"
                        alt="">
                </div>

                <div class="ratio ratio-1x1 d-block d-lg-none">
                    <img class="w-100"
                        src="https://images.unsplash.com/photo-1527525443983-6e60c75fff46?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=685&q=80"
                        alt="">
                </div>

                <ul>
                    <li>
                        Our aim is to uplift the living conditions of the community through
                        various programs, seminars, workshops, and activities that promote social, charitable,
                        humanitarian and philanthropic services. The organization aims to promote health
                        and family welfare, including the prevention of drug addiction, by providing healthcare
                        units, dispensaries, clinics, health-camps, de-addiction centers, and other allied
                        activities to promote community healthcare and nutrition. They also seek to promote economic
                        and social empowerment for women through microfinance and human resource development, among
                        other programs.
                    </li>
                    <div class="container d-none d-md-block">
                        <hr>
                    </div>
                    <li>
                        We empower the indigent and make them self-reliant and attain economic development to improve the living
                        standards of the people.
                    </li>
                    <div class="container d-none d-md-block">
                        <hr>
                    </div>
                    <li>
                        The organization intends to promote all-round development in society by establishing social
                        activities, economic development programs in agriculture, environment, medical and
                        educational spheres. They also seek to develop areas of mutual cooperation and understanding
                        among different voluntary agencies, organizations, institutions, government agencies,
                        groups, and individuals that are contributing to the welfare and development of the people.
                    </li>
                    <div class="container d-none d-md-block">
                        <hr>
                    </div>
                    <li>
                        The organization seeks to promote general welfare and physical, mental,
                        material, spiritual, moral, and cultural advancement of people irrespective of their
                        creed. We educate and train students, staff, social
                        workers, and others in arts, science, culture, religion, philosophy, theology, educational
                        skills, social action, etc.
                    </li>
                    <div class="container d-none d-md-block">
                        <hr>
                    </div>
                    <li>
                        This organization promotes the construction and running of schools, colleges, and non-formal
                        educational institutions based on the ideals laid by great educationists of the country for
                        the benefit of the public. We provide grants, scholarships, fellowships, and other forms
                        of financial assistance to the needy and deserving students for pursuing education, vocational
                        training, and skill development.
                    </li>
                    <div class="container d-none d-md-block">
                        <hr>
                    </div>
                    <li>
                        Finally, the organization aims to administer, organize, manage, encourage, associate,
                        supervise, promote, and carry out programs for the establishment and/or maintenance of
                        clinics, nursing homes, mobile clinics, vaccination and immunization centers, dispensaries,
                        hospitals, rehabilitation centers, health clubs and counseling centers for
                        the benefit of all irrespective of caste, creed, gender, or sect.
                    </li>
                </ul>
            </div>
        </div>
    </div>
</section>

{% include 'footer.html' %}
{% endblock content %}

fiid_india/templates/fiid_india/programmes.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'fiid_india/programmes_page/style.css' %}">
{% endblock styles %}


{% block content %}

{% include 'navbar.html' %}

<section id="programmes-overview">
    <div class="container">
        <a href="{% url 'fiid-india:home' %}">
            <button class="primary-btn go-back"><i class="fa-solid fa-arrow-left me-2"></i>Go back</button>
        </a>
        <div class="container-fluid">
            <h3 class="heading">Programmes overview</h3>
            <div class="ratio ratio-16x9 d-none d-lg-block">
                <img class="w-100"
                    src="https://images.unsplash.com/photo-1531058020387-3be344556be6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"
                    alt="">
            </div>
            <div class="ratio ratio-1x1 d-block d-lg-none">
                <img class="w-100"
                    src="https://images.unsplash.com/photo-1531058020387-3be344556be6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"
                    alt="">
            </div>
            <p>
                At FIID India, we believe that our mission and vision can be achieved
                through a holistic approach that addresses the root causes of poverty,
                inequality, and underdevelopment in rural communities. We undertake a wide
                range of activities to promote social welfare and economic development,
                including organizing various programs, seminars, activities, lectures,
                conferences, meetings, and workshops to create awareness and promote
                active involvement in social, charitable, humanitarian and philanthropic serivces
            </p>
            <p>
                Our main focuses is to promote health and family welfare. We
                recognize that access to basic healthcare services is a fundamental right of
                every individual, and we strive to make quality healthcare services available
                to rural communities across India. To achieve this, we organize health camps,
                awareness programs, and training sessions on various health-related issues,
                including sanitation, hygiene, nutrition, and reproductive health.
            </p>
        </div>
    </div>
</section>

<section id="core-programmes">
    <div class="container">
        <h3 class="heading main-heading">Our Core Programmes</h3>
        <div class="row row-cols-1 row-cols-lg-3 g-4">

            <div class="col">
                <div class="card h-100">
                    <img src="https://images.unsplash.com/photo-1581056771107-24ca5f033842?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"
                        class="card-img-top" alt="Skyscrapers" />

                    <div class="card-body">
                        <h5 class="card-title">Health Camps</h5>
                        <!--
                        <div class="card-footer">
                            <a href="#">
                                <button class="primary-btn">Know more<i
                                        class="fa-solid fa-arrow-right ms-2"></i></button>
                            </a>
                        </div>
                        -->
                    </div>
                </div>
            </div>

            <div class="col">
                <div class="card h-100">
                    <img src="https://images.unsplash.com/photo-1524178232363-1fb2b075b655?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"
                        class="card-img-top" alt="Los Angeles Skyscrapers" />

                    <div class="card-body">
                        <h5 class="card-title">Awareness Programmes</h5>

                        <!--
                        <div class="card-footer">
                            <a href="#">
                                <button class="primary-btn">Know more<i
                                        class="fa-solid fa-arrow-right ms-2"></i></button>
                            </a>
                        </div>
                        -->
                    </div>
                </div>
            </div>

            <div class="col">
                <div class="card h-100">
                    <img src="https://images.unsplash.com/photo-1512238972088-8acb84db0771?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"
                        class="card-img-top" alt="Palm Springs Road" />
                    <div class="card-body">
                        <h5 class="card-title">Training Sessions</h5>

                        <!--
                        <div class="card-footer">
                            <a href="#">
                                <button class="primary-btn">Know more<i
                                        class="fa-solid fa-arrow-right ms-2"></i></button>
                            </a>
                        </div>
                        -->
                    </div>
                </div>
            </div>

        </div>
</section>

{% include 'footer.html' %}
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FIID INDIA</title>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/title-icon.svg' %}">
    <link rel="stylesheet" href="{% static 'Bootstrap/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/all.min.css' %}">
    {% block styles %}{% endblock styles %}
</head>

<body>

    {% block content %}
    {% endblock content %}

    <script src="{% static 'Bootstrap/bootstrap.js' %}"></script>
    <script src="{% static 'fontawesome/all.min.js' %}"></script>
</body>

</html>

templates/footer.html
<footer class="text-center">
    ©️ 2021 FIID India | All rights reserved
</footer>

templates/navbar.html
{% load static %}

<header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'fiid-india:home' %}">
                <img src="{% static 'assets/logo.svg' %}" alt="">
            </a>
            <button class="navbar-toggler shadow-none" type="button" data-bs-toggle="offcanvas"
                data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar"
                aria-labelledby="offcanvasNavbarLabel">
                <div class="offcanvas-header">
                    <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Menu</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'fiid-india:about' %}">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'fiid-india:programmes' %}">Programmes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'fiid-india:objectives' %}">Objectives</a>
                        </li>
                        <!--
                        <li class="nav-item">
                            <a class="nav-link" href="#">Newsletter</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Gallery</a>
                        </li>
                        -->
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'fiid-india:contact' %}">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
</header>